### ISSUE TITLE
Training a model to predict time to last merger from kinetic data

### ISSUE THREAD

**Issue by EiffL** [EiffL/sfh-inference-hackathon#19]

**Comment by Siouar** [comment]
@ppfn mean and std from 100 samples : sigma: [18212.175615239412, 47.085832102830075, 29.16657788363947]
mean: [167915.38, 1.2179685, inf]
there are some issues with velocity dispersion 
NaN values found in velocity dispersion (replaced by 0)
then Inf values,...

**Comment by ppfn** [comment]
Thanks @Siouar.
For the NaN values, we have to decide to do:
Replacing with zeros, Interpolating data from nearby pixels, exclude the affected FITS file.
@mhuertascompany, any thought on that point ?

**Comment by ppfn** [comment]
Otherwise, I was able to train a model from a reduced dataset not affected by those NaN values.
Here is a plot of the predicted loopback times (in Gy) as a function of the true loopback times:
![Screenshot 2021-12-08 at 23 47 39](https://user-images.githubusercontent.com/20931653/145352824-c5a9267e-6420-4ab9-9ced-23d9995f4f98.png)
This is promising but, again, it was just on a reduced part of the dataset...

**Comment by Siouar** [comment]
sigma: [18212.175615239412, 47.085832102830075, 29.16650153197798]
mean: [167915.38, 1.2179685, 80.03517]

**Comment by mhuertascompany** [comment]
HI guys. For the NaN values, I do not know to be honest. Do we know how many images are affected by those? If the fraction is small I'd remove them from the training set. If it's large then, replacing by zeros is an option. Do we know how these NaN values are distributed in each galaxy? It is just one or two pixels? Or more than that?
